# Generated by Django 6.0 on 2025-12-11 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email_institucional", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=15, unique=True)),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Outro", "Outro"),
                            ("Prefiro não informar", "Prefiro não informar"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("Diretor", "Diretor"),
                            ("Assessora Administrativa", "Assessora Administrativa"),
                            (
                                "Núcleo de Tecnologia e Informação",
                                "Núcleo de Tecnologia e Informação",
                            ),
                            ("Coordenador", "Coordenador"),
                            ("Secretário", "Secretário"),
                            (
                                "Núcleo de Apoio Psicopedagógico",
                                "Núcleo de Apoio Psicopedagógico",
                            ),
                            ("Manutenção", "Manutenção"),
                        ],
                        max_length=40,
                    ),
                ),
                ("status_login", models.BooleanField(default=False)),
                ("dth_insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("dth_delete", models.DateTimeField(blank=True, null=True)),
                ("status_delete", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se este usuário deve ser tratado como ativo.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o usuário pode acessar este site de administração.",
                        verbose_name="Membro da Equipe",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="criador_por_matricula",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_criados",
                        to=settings.AUTH_USER_MODEL,
                        to_field="matricula",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "usuario",
            },
        ),
    ]
