# Generated by Django 6.0 on 2025-12-11 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salas", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_turma",
                    models.CharField(max_length=255, verbose_name="Código da turma"),
                ),
                ("data_inicial", models.DateField(blank=True, null=True)),
                ("data_final", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "criador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="matricula",
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="salas.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salas.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Matutino", "Matutino"),
                            ("Vespertino", "Vespertino"),
                            ("Noturno", "Noturno"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(max_length=255, verbose_name="Responsável"),
                ),
                (
                    "descricao_reserva",
                    models.TextField(verbose_name="Descrição da reserva"),
                ),
                (
                    "status_reserva",
                    models.BooleanField(default=True, verbose_name="Status da reserva"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas.reserva",
                        verbose_name="Reserva",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salas.sala",
                        verbose_name="Sala",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioOcupado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "periodo",
                    models.IntegerField(
                        choices=[
                            (1, "1º Período"),
                            (2, "2º Período"),
                            (3, "3º Período"),
                            (4, "4º Período"),
                        ]
                    ),
                ),
                (
                    "reserva_sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="reservas.reservasala",
                    ),
                ),
            ],
            options={
                "unique_together": {("reserva_sala", "dia_semana", "periodo")},
            },
        ),
    ]
